# The docker image information for the slack-music-notifications application
image:
  registry: index.docker.io
  repository: plexinc/slack-music-notifications
  # If unset use "latest"
  tag: "latest"
  sha: ""
  pullPolicy: IfNotPresent

ingress:
  # Specify if an ingress resource should be created or not
  enabled: false

  # The ingress class that should be used
  ingressClassName: "ingress-nginx"

  # The url to use for the ingress reverse proxy to point at this pms instance
  url: ""

  # Custom annotations to put on the ingress resource
  annotations: {}

secret:
  externalSecretKey: pms/corp/rclone-config

  # Custom annotations on the secret
  annotations: {}

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 256Mi
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

  # Port to use when type of service is "NodePort" (3000 by default)
  # nodePort: 3000

  # optional extra annotations to add to the service resource
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""

# Common Labels for all resources created by this chart.
commonLabels: {}

extraEnv: {}
# extraEnv:
  # This claim is optional, and is only used for the first startup of PMS
  # The claim is obtained from https://www.plex.tv/claim/ is is only valid for a few minutes
#   PLEX_CLAIM: "claim"
#   HOSTNAME: "PlexServer"
#   TZ: "Etc/UTC"
#   PLEX_UPDATE_CHANNEL: "5"
#   PLEX_UID: "uid of plex user"
#   PLEX_GID: "group id of plex user"
  # a list of CIDRs that can use the server without authentication
  # this is only used for the first startup of PMS
#   ALLOWED_NETWORKS: "0.0.0.0/0"

