{{- if .Values.secret.externalSecretKey  }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "music-notifications.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "music-notifications.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
  {{- .Values.secret.secretStore | toYaml | nindent 4 }}
  target:
    name: {{ include "music-notifications.fullname" . }}
    template:
      engineVersion: v2
      metadata:
        labels:
          {{- include "music-notifications.labels" . | nindent 10 }}
        annotations:
          {{- .Values.secret.annotations | toYaml  | nindent 10 }}
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.secret.externalSecretKey | quote }}
{{- end }}
