{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "music-notifications.fullname" . }}-ingress
  labels:
    name: {{ include "music-notifications.fullname" . }}-ingress
{{ include "music-notifications.labels" . | indent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
  - host: {{ trimPrefix "https://" .Values.ingress.url }}
    http:
      paths:
      - path: '/'
        pathType: Prefix
        backend:
          service:
            name: {{ include "music-notifications.fullname" . }}
            port:
              number: 3000
  tls:
  - hosts:
    - {{ trimPrefix "https://" .Values.ingress.url }}
    secretName: {{ include "music-notifications.fullname" . }}-ingress-lets-encrypt
{{- end -}}
