{{- if not .Values.secret.externalSecretKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "music-notifications.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "music-notifications.labels" . | nindent 4 }}
type: Opaque
data:
{{- .Values.secret.data | toYaml  | nindent 2 }}
{{- end }}
