apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-notifications.fullname" . }}
  labels:
    {{- include "music-notifications.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "3000" .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "music-notifications.selectorLabels" . | nindent 4 }}
