name: Deployment

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: plexinc/slack-music-notifications
        labels: |
          org.opencontainers.image.vendor=Plex, GmbH
        flavor: |
          latest=false
        tags: |
          type=ref,event=branch
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch,suffix=-{{sha}}
          type=ref,event=pr
          type=sha,prefix=,enable={{is_default_branch}}
          type=sha,enable={{is_default_branch}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64,linux/amd64/v2
