name: Helm

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
permissions:
  contents: read

jobs:

  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    runs-on: ubuntu-latest
    if: github.repository == 'plexinc/plex-slack-music-notifications'
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Artifact Hub lint
        run: |
          wget https://github.com/artifacthub/hub/releases/download/v1.5.0/ah_1.5.0_linux_amd64.tar.gz
          echo 'ad0e44c6ea058ab6b85dbf582e88bad9fdbc64ded0d1dd4edbac65133e5c87da *ah_1.5.0_linux_amd64.tar.gz' | shasum -c
          tar -xzvf ah_1.5.0_linux_amd64.tar.gz ah
          ./ah lint -p charts/music-notifications || exit 1
          rm -f ./ah ./ah_1.5.0_linux_amd64.tar.gz

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/music-notifications/Chart.yaml'
              - 'charts/music-notifications/values.yaml'

  chart:
    name: Release Chart
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    needs:
      - changes
    if: github.repository == 'plexinc/plex-slack-music-notifications' && needs.changes.outputs.charts == 'true'

    steps:
      - name: Checkout main
        uses: actions/checkout@v4 # v3.5.3
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_SKIP_EXISTING: "false"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
        with:
          charts_dir: charts
